### ISSUE TITLE
Open in Firefox (for Chromium) broken after upgrade to Ubuntu 19.10

### ISSUE THREAD

**Issue by fmichonneau** [andy-portmen/native-client#79]
I use the open in Firefox addon with Chromium on Ubuntu. After upgrading to Ubuntu 19.10, which uses a [snap-based](https://ubuntu.com/blog/chromium-in-ubuntu-deb-to-snap-transition) Chromium installation. The addon isn't working anymore. I suspect that the paths are altered with this transition but I have no knowledge of the technologies used here to be of more help without more guidance.

**Comment by andy-portmen** [comment]
Run your browser with "--enable-logging" argument and then try to use the extension as usual. See if you get anything useful in the console; https://developer.chrome.com/apps/nativeMessaging#native-messaging-debugging

Also, try to reinstall the native client once. I suspect the embedded NodeJS is not functioning after the upgrade.

**Comment by fmichonneau** [comment]
thanks @andy-portmen 

Here is what I see (after reinstalling the client):

> LaunchProcess: failed to execvp:
> /home/francois/.config/com.add0n.node/run.sh

**Comment by andy-portmen** [comment]
What do you get if you run "/home/francois/.config/com.add0n.node/run.sh" in a terminal window?

**Comment by fmichonneau** [comment]
There is no output (even if I try to click some links in Chromium while it's running).

**Comment by andy-portmen** [comment]
Google "LaunchProcess: failed to execvp:" for more info. Seems like it is related to running your browser as the root user.

**Comment by fmichonneau** [comment]
I'm running my web browser as a regular user, but I think it's a side effect of having chromium as a snap. Maybe it's this bug: <https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1732482>. I'm going to close here until it can be ruled out that it's not actually coming from the snap. Thanks for trying to troubleshoot.

**Comment by markstos** [comment]
I reproduced the issue and it's definitely related to the snap packaging, although it's not the same bug that was linked above. 

In this case the issue is that the installer puts files in `~/.config/chromium` but that file path is not used with the snap. Instead the correct directory for the snap would be like `~/snap/chromium/1005/.config`. Unfortunately the number you see in the path is a package version. I'm not certain that the snap format migrates this directory when the package is upgraded or if installing a file here a single time is sufficient for persistence through upgrades. 

On Ubuntu 19.10, trying to install the ".deb" file in the normal way will redirect the system automatically to installing the "snap", so this isn't a small issue-- unless something changes for Ubuntu 20.04, it's going to affect all Ubuntu / Chromium users. 

I doubt that the the Snap package is going to be modified to sure the `~/.config/chromium` directory so it might be up to this extension to add a new code path to handle this case. 

Fortunately, it's easy to detect: If `~/snap/chromium` exists, install there. On brand-new installs of Ubuntu 19.10, `~/.config/chromium` may also be empty or missing.

I think now that the issue is better understood the issue should be re-opened in this repo.

**Comment by oSoMoN** [comment]
Please note that the first time the chromium snap is run, it will look for and import an existing chromium profile under `~/.config/chromium`.

Also, there is a `current` symlink to the active revision number under `~/snap/chromium`, so you can refer to `~/snap/chromium/current` to make sure you're targetting an always current path. And on upgrades, the contents of the previous revision are copied over to the new revision, so no data is lost.

I hope that helps.
