### ISSUE TITLE
Reassurance native-client is Trustworthy

### ISSUE THREAD

**Issue by mossmoss** [andy-portmen/native-client#96]
Since native-client comes with a binary called node, can you note what that is and provide an md5 hash to compare against an official distribution (assuming it's not customized)?

One other possibility, make node a prerequisite instead of installing it? This would likely complicate installation, but might provide some reassurance - any other explicit information about the client / scripts, etc. and its requirements might also do the same.

**Comment by andy-portmen** [comment]
> can you note what that is and provide an md5 hash to compare against an official distribution 

Download the native client from releases and then run `./node --version` to find the version number. Then generate the MD5 and compare it with the official release. Based on commits, I would say we are on Node v10.16.3

https://github.com/andy-portmen/native-client/commit/7e9019a0579006ae0a20973acf2e3c8d8d33de82

> assuming it's not customized

No this project always uses an official version

> One other possibility, make node a prerequisite instead of installing it?

On Linux and Mac, the extension only uses the embedded NodeJS if there is no global one.

> any other explicit information about the client / scripts

If you check the source code of the native client, you will notice that this client only runs a virtual context to run the script that is sent from the extension side. So there is no complicated code in this client. The extension itself has both extension-side and native-side JavaScript codes so that both codes can get reviewed by the extension reviewers.
